Exams/Second Partial Exam/News/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * @author Konstantin Bogdanoski (konstantin.b@live.com)
 */

Route::get('/', function () {
    return view('welcome');
});

Route::get('/news/top', 'NewsController@top')->name('news.top');

Route::get('/news/{news}/upvote', 'NewsController@upvote')->name('news.upvote');

Route::get('/news/{news}/downvote', 'NewsController@downvote')->name('news.downvote');

Route::bind('news', function ($value, $route) {
    return App\News::where('id', $value)->first();
});

Route::bind('news.comments', function ($value, $route) {
    return App\Comment::where('id', $value)->first();
});

Route::resource('news', 'NewsController');

Route::resource('news.comments', 'CommentsController');

Exams/Second Partial Exam/News/app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
/**
 * @author Konstantin Bogdanoski (konstantin.b@live.com)
 */
class News extends Model
{
    protected $table = 'news';

    protected $fillable = ['news_description', 'news_link', 'news_title', 'num_upvotes', 'created_at'];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getRouteKeyName()
    {
        return 'id';
    }
}

Exams/Second Partial Exam/News/app/Http/Controllers/NewsController.php
<?php /** @noinspection PhpIncompatibleReturnTypeInspection */

namespace App\Http\Controllers;

use App\News;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/**
 * @author Konstantin Bogdanoski (konstantin.b@live.com)
 */
class NewsController extends Controller
{
    /**
     * Downvote news.
     *
     * @return Response
     */
    public function downvote(Request $request, News $news)
    {
        $news->num_upvotes = $news->num_upvotes - 1;
        if ($news->save()) {
            session()->flash('upvote', 'Downvoted');
        } else {
            session()->flash('upvote', 'Try to downvote again');
        }
        return back();
    }

    /**
     * Upvote news.
     *
     * @return Response
     */
    public function upvote(Request $request, News $news)
    {
        $news->num_upvotes = $news->num_upvotes + 1;
        if ($news->save()) {
            session()->flash('upvote', 'Upvoted');
        } else {
            session()->flash('upvote', 'Try to upvote again');
        }
        return back();
    }

    /**
     * Display top news.
     *
     * @return Response
     */
    public function top()
    {
        $news = News::all();
        $news->sortBy('num_upvotes');
        $topNews = [$news[0], $news[1], $news[2]];
        $news = $topNews;
        return view('news.index', compact('news'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $news = News::all();
        return view('news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $news = $this->validate(request(), [
            'news_description' => 'required',
            'news_link' => 'required|url',
            'news_title' => 'required|min:10',
            'created_at' => 'required|date',
            'num_upvotes' => 'required',
        ]);

        News::create($news);
        return redirect('/news')->with('success', 'News has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param News $news
     * @return Response
     */
    public function show(News $news)
    {
        return view('news.show', compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param News $news
     * @return Response
     */
    public function edit(News $news)
    {
        return view('news.edit', compact('news', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $this->validate(request(), [
            'news_description' => 'required',
            'news_link' => 'required|url',
            'news_title' => 'required',
            'num_upvotes' => 'required',
        ]);

        $news = News::where('id', $id->id)->first();
        $news->news_description = $request->get("news_description");
        $news->news_link = $request->get("news_link");
        $news->news_title = $request->get("news_title");
        $news->save();

        return redirect('/news')->with('success', 'News has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return Response
     */
    public function destroy($id)
    {
        $news = News::where('id', $id->id)->first();
        $news->delete();
        return redirect('/news')->with('success', 'News has been deleted');
    }
}

Exams/Second Partial Exam/News/resources/views/news/create.blade.php
@extends('app')
{{--@author Konstantin Bogdanoski (konstantin.b@live.com)--}}
@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br/>
        @endif
        <form method="post" action="{{url('news')}}">
            {{csrf_field()}}
            <input type="hidden" name="num_upvotes" value="0">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="news_title">Title</label>
                    <input id="news_title" type="text" class="form-control" name="news_title" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="news_description">Description</label>
                    <input id="news_description" type="text" class="form-control" name="news_description" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="news_link">Link</label>
                    <input id="news_link" type="url" class="form-control" name="news_link" pattern="https?://.+"
                           title="Include http://" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="created_at">Created at</label>
                    <input id="created_at" type="datetime-local" class="form-control" name="created_at" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2" style="margin-left: 300px">
                    <button type="submit" class="btn btn-success" style="margin-left:38px">Submit</button>
                </div>
                <div class="form-group col-md-2">
                    <button type="reset" class="btn btn-warning" style="margin-left:38px">Reset</button>
                </div>
                <div class="form-group col-md-2">
                    <button type="button" class="btn btn-danger" style="margin-left:38px"
                            onclick="location.href='/news'">Cancel
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection

Exams/Second Partial Exam/News/resources/views/news/edit.blade.php
@extends('app')
{{--@author Konstantin Bogdanoski (konstantin.b@live.com)--}}
@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br/>
        @endif
        <form method="post" action="{{action('NewsController@update', $news->id)}}">
            {{csrf_field()}}
            <input type="hidden" name="num_upvotes" value="0">
            <input type="hidden" name="_method" value="PATCH">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="news_title">Title</label>
                    <input id="news_title" type="text" class="form-control" name="news_title"
                           value="{{$news->news_title}}" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="news_description">Description</label>
                    <input id="news_description" type="text" class="form-control" name="news_description"
                           value="{{$news->news_description}}" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="news_link">Link</label>
                    <input id="news_link" type="url" class="form-control" name="news_link" value="{{$news->news_link}}"
                           required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="created_at">Created at</label>
                    <input id="created_at" type="datetime-local" class="form-control" name="created_at"
                           value="{{$news->created_at}}" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2" style="margin-left: 300px">
                    <button type="submit" class="btn btn-success" style="margin-left:38px">Submit</button>
                </div>
                <div class="form-group col-md-2">
                    <button type="reset" class="btn btn-warning" style="margin-left:38px">Reset</button>
                </div>
                <div class="form-group col-md-2">
                    <button type="button" class="btn btn-danger" style="margin-left:38px"
                            onclick="location.href='/news'">Cancel
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection

Exams/Second Partial Exam/News/resources/views/news/index.blade.php
@extends('app')
{{--@author Konstantin Bogdanoski (konstantin.b@live.com)--}}
@section('content')
    <div class="container">
        @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br/>
        @endif
        <table class="table table-striped">
            <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Upvotes
                </th>
                <th>
                    Comments
                </th>
                <th>
                    Date
                </th>
                <th>
                    Actions
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($news ?? '' as $new)
                <tr>
                    <td><a href="http://{{$new['news_link']}}">{{$new['news_title']}}</a></td>
                    <td>{{$new['num_upvotes']}}</td>
                    <td><a class="btn btn-info" style="width: 100%"
                           href="{{action('NewsController@show', $new['id'])}}">{{count($new->comments)}}</a></td>
                    <td>{{$new['created_at']}}</td>
                    <td>
                        <a href="{{action('NewsController@edit', $new['id'])}}"
                           class="btn btn-warning" style="width: 100%">
                            Edit
                        </a>
                        <form method="post" action="{{action('NewsController@destroy', $new['id'])}}">
                            {{csrf_field()}}
                            <input type="hidden" name="_method" value="DELETE">
                            <button style="width: 100%" type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="form-group col-md-2">
            <button type="button" class="btn btn-success" style="margin-left:38px"
                    onclick="location.href='/news/create'">Create News
            </button>
        </div>
    </div>
@endsection

Exams/Second Partial Exam/News/resources/views/news/show.blade.php
@extends('app')
{{--@author Konstantin Bogdanoski (konstantin.b@live.com)--}}
@section('content')
    <div class="frames-container-application text-center">
        <div class="jumbotron">
            <h1>{{$news['news_title']}}</h1>
            <div style="height: 5%">
                <a class="lead" href="{{$news['news_link']}}">Link to source</a><br>
                <span class="lead">{{$news['created_at']}}</span><br>
                <span class="lead font-weight-bold">
                    <span>Upvotes - {{$news['num_upvotes']}}</span>
                    <div class="container">
                        <a href="/news/{{$news['id']}}/upvote" class="btn btn-default">Upvote</a>
                        <a href="/news/{{$news['id']}}/downvote" class="btn btn-default">Downvote</a>
                    </div>
                </span>
            </div>
        </div>
    </div>
    <div class="container">
        @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br/>
        @endif
        @if (\Session::has('upvote'))
            <div class="alert alert-info">
                <p>{{ \Session::get('upvote') }}</p>
            </div><br/>
        @endif
        <div class="jumbotron" style="height: 50%">
                <span class="h2">
                    {{$news['news_description']}}
                </span>
        </div>
        <div class="frame-comments" style="height: 50%">
            <h2>Comments:</h2>
            @foreach($news->comments as $comment)
                <div class="jumbotron">
                    <div>
                        <div class="h3">
                            {{$comment['username']}}
                        </div>
                        <div>
                            {{$comment['created_at']}}
                        </div>
                    </div>
                    <div>
                        {{$comment['comment_text']}}
                    </div>
                    <div>
                        <a href="{{route('news.comments.edit', [$news['id'], $comment['id']])}}"
                           class="btn btn-warning" style="width: 100%">
                            Edit
                        </a>
                        <form method="post" action="{{route('news.comments.destroy', [$news['id'], $comment['id']])}}">
                            {{csrf_field()}}
                            <input type="hidden" name="_method" value="DELETE">
                            <button style="width: 100%" type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="container">
        <form method="post" action="{{'/news/'.$news['id'].'/comments'}}">
            {{csrf_field()}}
            <input type="hidden" name="news_id" value="{{$news['id']}}">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="username">Username</label>
                    <input id="username" type="text" class="form-control" name="username" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="comment_text">Comment</label>
                    <input id="comment_text" type="text" class="form-control" name="comment_text" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2" style="margin-left: 300px">
                    <button type="submit" class="btn btn-success" style="margin-left:38px">Submit</button>
                </div>
                <div class="form-group col-md-2">
                    <button type="reset" class="btn btn-warning" style="margin-left:38px">Reset</button>
                </div>
            </div>
        </form>
    </div>
@endsection