Exams/Second Partial Exam/News/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * @author Konstantin Bogdanoski (konstantin.b@live.com)
 */

Route::get('/', function () {
    return view('welcome');
});

Route::get('/news/top', 'NewsController@top')->name('news.top');

Route::get('/news/{news}/upvote', 'NewsController@upvote')->name('news.upvote');

Route::get('/news/{news}/downvote', 'NewsController@downvote')->name('news.downvote');

Route::bind('news', function ($value, $route) {
    return App\News::where('id', $value)->first();
});

Route::bind('news.comments', function ($value, $route) {
    return App\Comment::where('id', $value)->first();
});

Route::resource('news', 'NewsController');

Route::resource('news.comments', 'CommentsController');

Exams/Second Partial Exam/News/app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
/**
 * @author Konstantin Bogdanoski (konstantin.b@live.com)
 */
class Comment extends Model
{
    protected $table = 'comments';

    protected $fillable = ['news_id', 'username', 'comment_text'];

    public function news()
    {
        return $this->belongsTo(News::class);
    }

    public function getRouteKeyName()
    {
        return 'id';
    }
}

Exams/Second Partial Exam/News/app/Http/Controllers/CommentsController.php
<?php /** @noinspection PhpIncompatibleReturnTypeInspection */

namespace App\Http\Controllers;

use App\Comment;
use App\News;
use Illuminate\Http\Request;

/**
 * @author Konstantin Bogdanoski (konstantin.b@live.com)
 */
class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect('/news')->with('error', 'Bad request');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return redirect('/news')->with('error', 'Bad request');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $comment = $this->validate(request(), [
            'username' => 'required',
            'comment_text' => 'required',
            'news_id' => 'required|numeric'
        ]);
        Comment::create($comment);
        return redirect('/news/' . $request->get("news_id"))->with('success', 'Comment has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('/news')->with('error', 'Bad request');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news, Comment $comment)
    {
        $dbcomment = Comment::where('id', $comment->id)->first();
        $comment = $dbcomment;
        return view("comments.edit", compact('news'), compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, News $news, Comment $comment)
    {
        $this->validate(request(), [
            'username' => 'required',
            'comment_text' => 'required',
            'news_id' => 'required|numeric'
        ]);

        $dbcomment = Comment::where('id', $comment->id)->first();
        $dbcomment->comment_text = $request->get("comment_text");
        $dbcomment->save();

        return redirect('/news/' . $news->id)->with('success', 'Comment has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news, Comment $comment)
    {
        $dbcomment = Comment::where('id', $comment->id)->first();
        $dbcomment->delete();
        return redirect('/news/' . $news->id)->with('success', 'Comment has been deleted');
    }
}

Exams/Second Partial Exam/News/resources/views/comments/edit.blade.php
@extends('app')
{{--@author Konstantin Bogdanoski (konstantin.b@live.com)--}}
@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br/>
        @endif
        <form method="post" action="{{route('news.comments.update', [$news['id'], $comment['id']])}}">
            {{csrf_field()}}
            <input type="hidden" name="_method" value="PATCH">
            <input type="hidden" name="news_id" value="{{$news['id']}}">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="username">Username</label>
                    <input id="username" type="text" class="form-control" name="username" value="{{$comment->username}}"
                           required readonly>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="comment_text">Comment</label>
                    <input id="comment_text" type="text" class="form-control" name="comment_text"
                           value="{{$comment->comment_text}}" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2" style="margin-left: 300px">
                    <button type="submit" class="btn btn-success" style="margin-left:38px">Submit</button>
                </div>
                <div class="form-group col-md-2">
                    <button type="reset" class="btn btn-warning" style="margin-left:38px">Reset</button>
                </div>
                <div class="form-group col-md-2">
                    <button type="button" class="btn btn-danger" style="margin-left:38px"
                            onclick="location.href='{{'/news/'.$news['id']}}'">Cancel
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection